name: "manually triggered tf destroy"

on: workflow_dispatch

jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    env:
      TERRAFORM_DIR: terraform
      
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: terraform init
          working-directory: ${{ env.TERRAFORM_DIR }}
          env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform init

      - name: terraform destroy
        working-directory: ${{ env.TERRAFORM_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve

