name: "cloud resume backend deploy"

on:
  push:
    branches:
      - main

jobs:  
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Install boto 3
        run: pip install boto3

      - name: Install moto
        run: pip install moto
      
      - name: Install pytest
        run: pip install pytest

      - name: Test
        run: cd lambda && python -m pytest test.py && cd ..
  
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v2
      name: setup tflint
      with:
        tflint_version: v0.39.2

    - name: init tflint
      run: tflint --init

    - name: run tflint
      run: tflint -f compact

  terraform:
      name: "terraform"
      runs-on: ubuntu-latest
      env:
        TERRAFORM_DIR: terraform
      needs: [pytest,tflint]

      defaults:
        run:
          shell: bash

      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: terraform setup
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.2.4
            terraform_wrapper: false

        - name: terraform init
          working-directory: ${{ env.TERRAFORM_DIR }}
          env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform init
        
        - name: terraform fmt
          working-directory: ${{ env.TERRAFORM_DIR  }}
          run: terraform fmt -check

        - name: terraform plan
          working-directory: ${{ env.TERRAFORM_DIR  }}
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform plan
        
        - name: terraform apply
          working-directory: ${{ env.TERRAFORM_DIR  }}
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve      